# -*- coding: utf-8 -*-
"""mids1Titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1evI9Jbz7bZ5lepS0KHyujiZVLEqSwW9u
"""

import pandas as pd
import numpy as np

df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
print(df.head())

print(df.isnull().sum())

# Fill missing values
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
df['Sex'] = df['Sex'].fillna(df['Sex'].mode()[0])  # just in case

# Check unique values before mapping
print(df['Sex'].unique())
print(df['Embarked'].unique())

# Drop unnecessary columns (ignore if missing)
df = df.drop(columns=['Cabin'], errors='ignore')
df = df.drop(columns=['Name', 'Ticket', 'PassengerId'], errors='ignore')

# Convert categorical to numeric
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
df['Embarked'] = df['Embarked'].map({'C': 0, 'Q': 1, 'S': 2})

print(df.head())

df.to_csv("titanic_preprocessed.csv", index=False)