# -*- coding: utf-8 -*-
"""sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zTeBIfQ4fUCqG2XEoucu0548Cfooa0Sx
"""

import pandas as pd
from textblob import TextBlob
from sklearn.metrics import accuracy_score, classification_report

# Load Dataset
train_url = "https://raw.githubusercontent.com/Vasistareddy/sentiment_analysis/master/data/train.csv"
test_url = "https://raw.githubusercontent.com/Vasistareddy/sentiment_analysis/master/data/test.csv"

train_df = pd.read_csv(train_url)
test_df = pd.read_csv(test_url)

# Function to compute polarity
def get_polarity(text):
    return TextBlob(text).sentiment.polarity

# Apply polarity to test data
test_df['polarity'] = test_df['Content'].apply(get_polarity)

# Classify based on polarity
test_df['predicted_label'] = test_df['polarity'].apply(lambda x: 1 if x > 0 else 0)

# 🔁 Convert true labels from 'pos'/'neg' to 1/0
test_df['Label'] = test_df['Label'].map({'pos': 1, 'neg': 0})

# Evaluation
print("Accuracy:", accuracy_score(test_df['Label'], test_df['predicted_label']))
print("\nClassification Report:\n", classification_report(test_df['Label'], test_df['predicted_label']))